### PR TITLE
Add windows amd64 build target

### PR DESCRIPTION
**Pull request by kevcodez**
Kept the executable name for linux to not make any breaking changes.

### CODE REVIEW

**Comment by felixb** [comment]
Thanks for the contribution.
I'd like you to change the executable name to `cpfw-login.exe` or `cpfw-login-amd64.exe`.

**Comment by kevcodez** [comment]
@felixb Done ;)

**Comment by kevcodez** [comment]
@felixb Like this?

```
cpfw-login.exe: .get-deps *.go
	 GOOS=windows GOARCH=amd64 go build -o $@ .
```

I'm not familiar with go, so I don't really know better.

**Comment by felixb** [comment]
It's not about go. It's about make.

But yes. that's correct. You need to change the make target in line 5 as well.

**Pull request merged**
